version: '3'

services:
  redis:
    image: 'redis:4-alpine'
    container_name: "redis"
    ports:
      - '6379:6379'

  postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=pg_mdn_company
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    command:
      - "postgres"
      - "-c"
      - "effective_cache_size=1024MB"
    networks:
      - network-backend
    volumes:
      - ./srv/docker/postgresql:/var/lib/postgresql

networks:
  network-backend:
    driver: bridge