DO $$
BEGIN
  CREATE TABLE COMPANY (
    COMPANY_ID UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
    NAME VARCHAR(100) NOT NULL,
    IDENTIFICATION_NUMBER VARCHAR(15) NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL,
    ADDRESS_NUMBER VARCHAR(10) NOT NULL,
    ADDITIONAL VARCHAR(100) NOT NULL,
    ZIP_CODE VARCHAR(10) NOT NULL,
    NEIGHBORHOOD VARCHAR(100) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    UF VARCHAR(2) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PHONE_NUMBER VARCHAR(20) NOT NULL,
    CONSTRAINT COMPANY_PK PRIMARY KEY (COMPANY_ID)
  );

  COMMENT ON  TABLE COMPANY IS 'Table to store Companies';
  COMMENT ON COLUMN COMPANY.COMPANY_ID IS 'The Company Id in this table.';
  COMMENT ON COLUMN COMPANY.NAME IS 'The Name in this table.';
  COMMENT ON COLUMN COMPANY.IDENTIFICATION_NUMBER IS 'The Identification Number in this table.';
  COMMENT ON COLUMN COMPANY.TYPE IS 'The Type in this table.';
  COMMENT ON COLUMN COMPANY.ADDRESS IS 'The Address in this table.';
  COMMENT ON COLUMN COMPANY.ADDRESS_NUMBER IS 'The Address Number in this table.';
  COMMENT ON COLUMN COMPANY.ADDITIONAL IS 'The Additional in this table.';
  COMMENT ON COLUMN COMPANY.ZIP_CODE IS 'The Zip Code in this table.';
  COMMENT ON COLUMN COMPANY.NEIGHBORHOOD IS 'The Neighborhood in this table.';
  COMMENT ON COLUMN COMPANY.CITY IS 'The City in this table.';
  COMMENT ON COLUMN COMPANY.UF IS 'The UF in this table.';
  COMMENT ON COLUMN COMPANY.EMAIL IS 'The e-Mail in this table.';
  COMMENT ON COLUMN COMPANY.PHONE_NUMBER IS 'The Phone Number in this table.';
 END
$$;